# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nschwob <nschwob@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/25 04:14:23 by nschwob           #+#    #+#              #
#    Updated: 2022/11/25 04:21:14 by nschwob          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libftprintf.a

SRCS =	

$(NAME)

CFLAGS = -Wall, -Wextra et -Werror

CC = gcc $(CFLAGS)

RM = rm -f

all:	$(NAME)

clean:	$(RM)

fclean:	clean 
		$(RM)	$(NAME)

re:		fclean all